package dev.rambris.tunnellen;

import ch.qos.logback.classic.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.Socket;
import java.security.SecureRandom;
import java.util.Random;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

/**
 * One shared, per-cluster SOCKS5 proxy tunnel (Phase 1 of BIG-REFACTOR.md).
 *
 * <p>Runs a single ephemeral {@code serjs/go-socks5-proxy} pod in the target
 * cluster ({@code context}), forwards a local port to it via {@code kubectl
 * port-forward}, and exposes per-run randomly generated (or overridden)
 * SOCKS5 username/password credentials. Service tunnels (Phase 2) are meant
 * to ride through the local port this class opens, rather than each opening
 * their own {@code kubectl port-forward}.
 *
 * <h2>Manual verification performed (see BIG-REFACTOR.md 1.1 / 1.1a)</h2>
 *
 * <p>Verified for real against the {@code bhg-dev} GKE cluster on 2026-08-18:
 * <pre>
 *   kubectl --context=bhg-dev apply -f - &lt;&lt;EOF
 *   apiVersion: v1
 *   kind: Pod
 *   metadata:
 *     name: tunnellen-verify-x7q2k9
 *     namespace: default
 *   spec:
 *     restartPolicy: Never
 *     containers:
 *     - name: socks
 *       image: serjs/go-socks5-proxy
 *       ports:
 *       - containerPort: 1080
 *       env:
 *       - name: PROXY_USER
 *         value: "testuser"
 *       - name: PROXY_PASSWORD
 *         value: "testpass"
 *   EOF
 *   kubectl --context=bhg-dev wait --for=condition=Ready pod/tunnellen-verify-x7q2k9 --timeout=60s
 *   kubectl --context=bhg-dev port-forward pod/tunnellen-verify-x7q2k9 11080:1080 &amp;
 *   curl --socks5-hostname testuser:testpass@127.0.0.1:11080 \
 *        http://accounting-service.default.svc.cluster.local:8080/   # -&gt; HTTP 404 (reached the service)
 *   curl --socks5-hostname 127.0.0.1:11080        ... same URL        # -&gt; connect failure, no creds supplied
 *   curl --socks5-hostname wrong:wrong@127.0.0.1:11080 ... same URL   # -&gt; connect failure, wrong creds
 *   kubectl --context=bhg-dev delete pod tunnellen-verify-x7q2k9 --wait=false
 * </pre>
 *
 * <h3>Observed behavior / deviations from the plan's assumptions</h3>
 * <ul>
 *   <li>{@code serjs/go-socks5-proxy} became Ready within a few seconds of
 *       apply — no readiness probe surprises; {@code kubectl wait
 *       --for=condition=Ready --timeout=60s} was more than enough (the plan's
 *       {@code --timeout=30s} in 1.2's prose also works fine in practice, but
 *       this class uses 60s for headroom on a busy/cold node).</li>
 *   <li>{@code PROXY_USER}/{@code PROXY_PASSWORD} behave exactly as
 *       documented: both set enables SOCKS5 username/password auth (RFC
 *       1929); a request with no credentials or with wrong credentials is
 *       rejected outright by the proxy (SOCKS5 handshake fails, {@code curl}
 *       reports a connect error) rather than e.g. silently allowing through
 *       or returning an HTTP-level 401.</li>
 *   <li>A correctly authenticated SOCKS5 connection to a real in-cluster
 *       {@code Service} DNS name ({@code accounting-service.default.svc.cluster.local:8080})
 *       reached the service and got a normal HTTP response (404 for
 *       requesting {@code /} on a service with no such route) — end-to-end
 *       proof the pod's SOCKS proxy can resolve and reach cluster-internal
 *       DNS/services regardless of the proxy pod's own namespace, as the
 *       plan assumed.</li>
 *   <li>{@code kubectl apply -f -} (manifest via stdin) was used instead of
 *       {@code kubectl run ... --overrides=...} — more reliable for setting
 *       multiple env vars and easier to unit-construct as a Java string, per
 *       the plan's own suggestion.</li>
 * </ul>
 *
 * <h3>Credential strategy (1.1a)</h3>
 * Per-run random credentials are the default: {@link #generateCredential()}
 * produces a 24-character alphanumeric token via {@link SecureRandom}, and a
 * fresh username/password pair is generated by the no-override constructor.
 * An explicit static override may be passed to the other constructor instead
 * (e.g. sourced from {@code forwards.yaml} in a later step). Credentials are
 * held only in memory and are logged at DEBUG level at most, never at INFO,
 * to avoid leaking them into normal log output.
 */
public class ClusterSocksTunnel {
    private static final String NAMESPACE = "default";
    private static final String IMAGE = "serjs/go-socks5-proxy";
    private static final String CREDENTIAL_CHARS =
            "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    private static final SecureRandom RANDOM = new SecureRandom();

    private final Logger log;
    private final String context;
    private final int localPort;
    private final String podName;
    private final String username;
    private final String password;

    private Process portForwardProcess = null;
    private AsyncInputStreamReader outputReader;

    /**
     * Creates a cluster SOCKS tunnel with freshly generated random
     * credentials (the recommended default per 1.1a).
     */
    public ClusterSocksTunnel(String context, int localPort) {
        this(context, localPort, generateCredential(), generateCredential());
    }

    /**
     * Creates a cluster SOCKS tunnel with an explicit static username/password
     * override (fallback path per 1.1a, e.g. for stable/shared/scripted
     * credentials). The pod-name suffix identifying this developer falls back
     * to the {@code user.name} system property here (fails fast if unset) --
     * callers that already have a resolved suffix (e.g. {@code Main}, which
     * checks {@code Configuration.socksPodSuffix()} first) should use the
     * five-argument constructor instead.
     */
    public ClusterSocksTunnel(String context, int localPort, String username, String password) {
        this(context, localPort, username, password, requireOsUsername());
    }

    /**
     * Creates a cluster SOCKS tunnel with an explicit static username/password
     * override AND an explicit pod-name suffix (identifying this developer),
     * bypassing the {@code user.name} system-property fallback entirely. Used
     * by {@code Main} once it has resolved the suffix via {@code
     * Configuration.socksPodSuffix()} / {@code user.name} / fail-fast -- see
     * {@code Main#resolveSocksPodSuffix(Configuration)}.
     */
    public ClusterSocksTunnel(String context, int localPort, String username, String password, String podSuffix) {
        this.log = (Logger) LoggerFactory.getLogger("clustersocks." + context + "[" + localPort + "]");
        this.context = context;
        this.localPort = localPort;
        if (podSuffix == null || podSuffix.isBlank()) {
            throw new IllegalStateException("No SOCKS pod-name suffix available -- this is required to " +
                    "give each developer their own SOCKS proxy pod per cluster and avoid colliding with " +
                    "other developers' tunnellen instances.");
        }
        this.podName = "tunnellen-socks-" + slugifyUsername(podSuffix);
        this.username = username;
        this.password = password;
    }

    /**
     * Resolves the current OS username via the {@code user.name} system
     * property, failing fast (rather than silently falling back to a generic
     * name that would reintroduce pod-name collisions between developers) if
     * it's unset or blank.
     */
    private static String requireOsUsername() {
        var osUsername = System.getProperty("user.name");
        if (osUsername == null || osUsername.isBlank()) {
            throw new IllegalStateException("Cannot determine the current OS username (system property " +
                    "'user.name' is not set) -- this is required to give each developer their own SOCKS " +
                    "proxy pod per cluster and avoid colliding with other developers' tunnellen instances. " +
                    "Set it explicitly, e.g. -Duser.name=<yourname>, or set socksPodSuffix in your config " +
                    "file, and try again.");
        }
        return osUsername;
    }

    /**
     * Generates a random 24-character alphanumeric credential token via
     * {@link SecureRandom}. Shared helper used by default for both username
     * and password when no static override is supplied.
     */
    public static String generateCredential() {
        var sb = new StringBuilder(24);
        for (int i = 0; i < 24; i++) {
            sb.append(CREDENTIAL_CHARS.charAt(RANDOM.nextInt(CREDENTIAL_CHARS.length())));
        }
        return sb.toString();
    }

    /**
     * Turns an OS username into a valid Kubernetes pod-name segment: lowercased,
     * anything that isn't {@code [a-z0-9-]} collapsed to a single {@code -}, and
     * leading/trailing {@code -} trimmed. Falls back to {@code "user"} if that
     * leaves nothing usable (e.g. an all-symbol username).
     *
     * <p>Multiple developers each running {@code tunnellen} against the same
     * cluster get their own pod (named {@code tunnellen-socks-<their-username>})
     * rather than colliding on a shared, context-only name — see the discussion
     * around this in BIG-REFACTOR.md: without this, the second developer to
     * start up would delete-then-replace the first developer's still-running
     * proxy pod via {@link #deleteStalePod()}'s stale-pod cleanup.
     */
    static String slugifyUsername(String username) {
        if("*".equals(username)) return AlphaGenerator.generate(10);

        var slug = username.toLowerCase(java.util.Locale.ROOT)
                .replaceAll("[^a-z0-9-]+", "-")
                .replaceAll("^-+|-+$", "");
        return slug.isEmpty() ? "user" : slug;
    }

    private String manifestYaml() {
        return """
                apiVersion: v1
                kind: Pod
                metadata:
                  name: %s
                  namespace: %s
                spec:
                  restartPolicy: Never
                  containers:
                  - name: socks
                    image: %s
                    ports:
                    - containerPort: 1080
                    env:
                    - name: PROXY_USER
                      value: "%s"
                    - name: PROXY_PASSWORD
                      value: "%s"
                """.formatted(podName, NAMESPACE, IMAGE, username, password);
    }

    public void start() {
        log.debug("Generated credentials: username={} password=<redacted>", username);
        deleteStalePod();
        if (!applyPod()) {
            log.warn("Failed to create cluster SOCKS pod, aborting start");
            return;
        }
        if (!waitForReady()) {
            log.warn("Cluster SOCKS pod did not become Ready in time");
            return;
        }
        startPortForward();
    }

    /**
     * Best-effort delete of any stale pod left over from a previous run, BLOCKING
     * until it's actually gone (not just until the delete is accepted) before
     * {@link #start()} moves on to {@link #applyPod()}.
     *
     * <p>Originally used {@code --wait=false}, which returns as soon as the API
     * server accepts the delete -- not once the pod has actually terminated. If
     * the previous run's pod hadn't finished terminating yet (e.g. this process
     * was killed abruptly, skipping its shutdown hook, and got restarted quickly),
     * the immediately-following {@code kubectl apply} would hit the still-existing
     * pod and try to patch its (immutable) {@code spec.containers[*].env} with this
     * run's freshly-generated credentials -- Kubernetes rejects that outright
     * ("Pod ... is invalid: spec: Forbidden: pod updates may not change fields
     * other than ..."), so {@code start()} would abort. Waiting for the real
     * deletion here removes that race.
     */
    private void deleteStalePod() {
        var cmd = new String[]{
                "kubectl", "--context=" + context, "delete", "pod", podName,
                "--namespace", NAMESPACE, "--ignore-not-found", "--timeout=40s"
        };
        try {
            var proc = new ProcessBuilder(cmd).redirectErrorStream(true).start();
            var finished = proc.waitFor(45, TimeUnit.SECONDS);
            if (!finished || proc.exitValue() != 0) {
                log.warn("Stale pod delete for {} did not finish cleanly within the timeout " +
                        "(pod may still be terminating) -- the apply that follows may fail and " +
                        "will be retried on the next keepalive cycle", podName);
            }
        } catch (IOException | InterruptedException e) {
            if (e instanceof InterruptedException) {
                Thread.currentThread().interrupt();
            }
            log.debug("Best-effort stale pod delete failed (ignored): {}", e.getMessage());
        }
    }

    private boolean applyPod() {
        var cmd = new String[]{"kubectl", "--context=" + context, "apply", "-f", "-"};
        try {
            var proc = new ProcessBuilder(cmd).redirectErrorStream(true).start();
            proc.getOutputStream().write(manifestYaml().getBytes());
            proc.getOutputStream().close();
            var reader = new AsyncInputStreamReader(proc.getInputStream(), log::info);
            boolean finished = proc.waitFor(30, TimeUnit.SECONDS);
            reader.stop();
            if (!finished || proc.exitValue() != 0) {
                log.warn("kubectl apply for cluster SOCKS pod did not succeed cleanly");
                return false;
            }
            log.info("Applied cluster SOCKS pod {}", podName);
            return true;
        } catch (IOException | InterruptedException e) {
            if (e instanceof InterruptedException) {
                Thread.currentThread().interrupt();
            }
            log.warn("Failed to apply cluster SOCKS pod: {}", e.getMessage());
            return false;
        }
    }

    private boolean waitForReady() {
        var cmd = new String[]{
                "kubectl", "--context=" + context, "wait",
                "--for=condition=Ready", "pod/" + podName,
                "--namespace", NAMESPACE, "--timeout=30s"
        };
        try {
            var proc = new ProcessBuilder(cmd).redirectErrorStream(true).start();
            var reader = new AsyncInputStreamReader(proc.getInputStream(), log::info);
            boolean finished = proc.waitFor(40, TimeUnit.SECONDS);
            reader.stop();
            return finished && proc.exitValue() == 0;
        } catch (IOException | InterruptedException e) {
            if (e instanceof InterruptedException) {
                Thread.currentThread().interrupt();
            }
            log.warn("Failed waiting for cluster SOCKS pod readiness: {}", e.getMessage());
            return false;
        }
    }

    private void startPortForward() {
        var cmd = new String[]{
                "kubectl", "--context=" + context, "port-forward",
                "pod/" + podName, localPort + ":1080",
                "--namespace", NAMESPACE
        };
        try {
            portForwardProcess = new ProcessBuilder(cmd).start();
            log.info("Started cluster SOCKS port-forward on local port {}", localPort);
            outputReader = new AsyncInputStreamReader(portForwardProcess.getInputStream(), this::handleOutput);
        } catch (IOException e) {
            log.warn("Failed to start cluster SOCKS port-forward: {}", e.getMessage());
        }
    }

    private void handleOutput(String line) {
        log.info(line);
    }

    public boolean isRunning() {
        return portForwardProcess != null && portForwardProcess.isAlive();
    }

    public boolean isAlive() {
        try (var sock = new Socket()) {
            log.debug("Checking cluster SOCKS tunnel");
            sock.connect(new InetSocketAddress(InetAddress.getLoopbackAddress(), localPort), 2000);
            log.debug("Cluster SOCKS tunnel is alive");
            return true;
        } catch (IOException e) {
            log.debug("Cluster SOCKS tunnel is not alive: {}", e.getMessage());
            return false;
        }
    }

    public void stop() {
        if (portForwardProcess != null && portForwardProcess.isAlive()) {
            log.info("Stopping cluster SOCKS port-forward");
            portForwardProcess.destroy();
            if (outputReader != null) {
                outputReader.stop();
            }
            try {
                portForwardProcess.waitFor(10, TimeUnit.SECONDS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
            log.info("Cluster SOCKS port-forward stopped");
        }
        portForwardProcess = null;

        var cmd = new String[]{
                "kubectl", "--context=" + context, "delete", "pod", podName,
                "--namespace", NAMESPACE, "--wait=false"
        };
        try {
            new ProcessBuilder(cmd).redirectErrorStream(true).start();
            log.info("Requested deletion of cluster SOCKS pod {}", podName);
        } catch (IOException e) {
            log.warn("Failed to request deletion of cluster SOCKS pod: {}", e.getMessage());
        }
    }

    public String getContext() {
        return context;
    }

    public int getLocalPort() {
        return localPort;
    }

    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }
}
